# Generated by Django 5.2.1 on 2025-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='duration_in_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
